version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "8080:80/tcp"
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: 'example' 
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    restart: unless-stopped